version: '3.8'

services:

  redis:
    image: "redis:alpine"
    container_name: redis

  backend:
    volumes:
      - static:/static
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis


  frontend:
    build:
      context: ./vue
      dockerfile: Dockerfile
    volumes:
      - vue_build:/vue/build
    depends_on:
      - backend
  
  nginx:
    image: "nginx:latest"
    volumes:
      - static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - vue_build:/var/www/vue
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend


volumes:
  static:
  vue_build:




